/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quadtree;

import java.awt.Color;
import java.awt.Graphics;
import java.util.Random;
import javax.swing.SwingUtilities;
/**
 *
 * @author Buğra
 */
public class NewJFrame extends javax.swing.JFrame {

 QuadTree n1= new QuadTree();

 public static int s1,s2,i=0;

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Random");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.setAlignmentX(0.0F);
        jPanel2.setAlignmentY(0.0F);
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setName(""); // NOI18N
        jPanel2.setNextFocusableComponent(jPanel2);
        jPanel2.setPreferredSize(new java.awt.Dimension(512, 512));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jButton2.setText("Temizle");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            
        String b;
        b=jTextField1.getText();
        int sayac=Integer.parseInt(b);
        
        while(i<sayac)
            {
            int minx, miny, maxx, maxy;
 
            Random r = new Random();
            int rx=r.nextInt(500); //ekran boyutuna göre x değeri al
            int ry=r.nextInt(500); //ekran boyutuna göre y değeri al
         
           
            int rs = r.nextInt(255);
            int gs = r.nextInt(255);
            int bs = r.nextInt(255);
            Color randomColor = new Color(rs, gs, bs);
            n1.bolgebul(rx, ry);
            s2=n1.sayi2; 
            Graphics g = jPanel2.getGraphics();     
            g.setColor(randomColor);
            
            if(s2==0){   
                            
               minx=0;
               maxx=512;
               miny=0;
               maxy=512;
               n1.insert(rx, ry, minx, miny, maxx, maxy);
               g.fillArc(rx, ry, 5, 5, 0, 360);
               g.drawLine(minx, ry, maxx, ry);
               g.drawLine(rx, miny, rx, maxy);
                System.out.println("asd");
            }
           else if (s2==1){  
                
          
                minx=(int)n1.minx;
                maxx=(int)n1.xx;
                miny=(int)n1.yy;
                maxy=(int)n1.maxy;
                n1.insert(rx, ry, minx, miny, maxx, maxy);
                g.fillArc(rx, ry, 5, 5, 0, 360);
                g.drawLine((int)n1.minx, ry, (int)n1.maxx,ry );
                g.drawLine(rx, (int)n1.miny, rx, (int)n1.maxy );
                
               
                
            }
             else if(s2==2){
            
                
                minx=(int)n1.minx;
                maxx=(int)n1.xx;
                miny=(int)n1.miny;
                maxy=(int)n1.yy;
                n1.insert(rx, ry, minx, miny, maxx, maxy);
                g.fillArc(rx, ry, 5, 5, 0, 360);
                g.drawLine((int)n1.minx, ry, (int)n1.maxx,ry );
                g.drawLine(rx, (int)n1.miny, rx, (int)n1.maxy );
             
             
      
           
           }
           else if(s2==3){
               
               minx=(int)n1.xx;
               maxx=(int)n1.maxx;
               miny=(int)n1.yy;
               maxy=(int)n1.maxy;
               n1.insert(rx, ry, minx, miny, maxx, maxy);
               g.fillArc(rx, ry, 5, 5, 0, 360);  
               g.drawLine((int)n1.minx, ry, (int)n1.maxx,ry );
               g.drawLine(rx, (int)n1.miny, rx, (int)n1.maxy );;
           
            
            }
           else if(s2==4){
                
               minx=(int)n1.xx;
               maxx=(int)n1.maxx;
               miny=(int)n1.miny;
               maxy=(int)n1.yy;
               n1.insert(rx, ry, minx, miny, maxx, maxy);
               g.fillArc(rx, ry, 5, 5, 0, 360);
               g.drawLine((int)n1.minx, ry, (int)n1.maxx,ry );
               g.drawLine(rx, (int)n1.miny, rx, (int)n1.maxy );;
           
            }
              i++;
            }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
            int x,y;
            x=evt.getX();
            y=evt.getY(); 
            if(SwingUtilities.isRightMouseButton(evt))
            {
                String a;
                int yaricap;
                a=jTextField1.getText();
                yaricap=Integer.parseInt(a);
                Graphics daire=jPanel2.getGraphics();
                daire.setColor(Color.yellow);
                daire.drawArc(x-(yaricap/2), y-(yaricap/2), yaricap, yaricap, 0, 360);
                n1.ara(x-yaricap,x+yaricap,y-yaricap,y+yaricap);        
            }
            else
            {
            Random r = new Random();
            int minx, miny, maxx, maxy;     
            int rs = r.nextInt(255);
            int gs = r.nextInt(255);
            int bs = r.nextInt(255);
            Color randomColor = new Color(rs, gs, bs);  
            Graphics g = jPanel2.getGraphics();
            g.setColor(randomColor);
            n1.bolgebul(x, y);
            s2=n1.sayi2;
            if(s2==0){   
               minx=0;
               maxx=512;
               miny=0;
               maxy=512;
               n1.insert(x, y, minx, miny, maxx, maxy);
               g.fillArc(x, y, 5, 5, 0, 360);
               g.drawLine(minx, y, maxx, y);
               g.drawLine(x, miny, x, maxy);
               
            
              }
           
          
      
             else if (s2==1){  
                
          
                minx=(int)n1.minx;
                maxx=(int)n1.xx;
                miny=(int)n1.yy;
                maxy=(int)n1.maxy;
                n1.insert(x, y, minx, miny, maxx, maxy);
                g.fillArc(x, y, 5, 5, 0, 360);
                g.drawLine((int)n1.minx, y, (int)n1.maxx,y );
                g.drawLine(x, (int)n1.miny, x, (int)n1.maxy );
                
               
                
            }
             else if(s2==2){
            
                
                minx=(int)n1.minx;
                maxx=(int)n1.xx;
                miny=(int)n1.miny;
                maxy=(int)n1.yy;
                n1.insert(x, y, minx, miny, maxx, maxy);
                g.fillArc(x, y, 5, 5, 0, 360);
                g.drawLine((int)n1.minx, y, (int)n1.maxx,y );
                g.drawLine(x, (int)n1.miny, x, (int)n1.maxy );
             
             
      
           
           }
           else if(s2==3){
               
               minx=(int)n1.xx;
               maxx=(int)n1.maxx;
               miny=(int)n1.yy;
               maxy=(int)n1.maxy;
               n1.insert(x, y, minx, miny, maxx, maxy);
               g.fillArc(x, y, 5, 5, 0, 360);  
               g.drawLine((int)n1.minx, y, (int)n1.maxx,y );
               g.drawLine(x, (int)n1.miny, x, (int)n1.maxy );;
           
            
            }
           else if(s2==4){
                
               minx=(int)n1.xx;
               maxx=(int)n1.maxx;
               miny=(int)n1.miny;
               maxy=(int)n1.yy;
               n1.insert(x, y, minx, miny, maxx, maxy);
               g.fillArc(x, y, 5, 5, 0, 360);
               g.drawLine((int)n1.minx, y, (int)n1.maxx,y );
               g.drawLine(x, (int)n1.miny, x, (int)n1.maxy );;
           
            }
              
            }
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //DOKTOR YARIN YAPACAK
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
         
       
  
   
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new NewJFrame().setVisible(true);
        });
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    public javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

  
}
